name: ExposedTest
version: '${version}'
main: org.gang.afreekaplugin.AfreeKaPlugin
api-version: '1.20'
libraries:
  - xyz.icetang.lib:kommand-core:3.1.11
  - io.github.monun:invfx-core:3.3.2
  - io.github.monun:heartbeat-coroutines:0.0.5
  - org.jetbrains.exposed:exposed-core:0.48.0
  - org.jetbrains.exposed:exposed-crypt:0.48.0
  - org.jetbrains.exposed:exposed-dao:0.48.0
  - org.jetbrains.exposed:exposed-jdbc:0.48.0
  - org.jetbrains.exposed:exposed-kotlin-datetime:0.48.0
  - org.jetbrains.exposed:exposed-json:0.48.0
  - org.jetbrains.exposed:exposed-money:0.48.0
